Search.appendIndex(
    [
                {
            "fqsen": "\\obtainToken\u0028\u0029",
            "name": "obtainToken",
            "summary": "",
            "url": "namespaces/default.html#function_obtainToken"
        },                {
            "fqsen": "\\getAllUsers\u0028\u0029",
            "name": "getAllUsers",
            "summary": "",
            "url": "namespaces/default.html#function_getAllUsers"
        },                {
            "fqsen": "\\getUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "namespaces/default.html#function_getUser"
        },                {
            "fqsen": "\\authenticate\u0028\u0029",
            "name": "authenticate",
            "summary": "",
            "url": "namespaces/default.html#function_authenticate"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController",
            "name": "PersonController",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020de\u0020la\u0020clase\u0020PersonController.php",
            "url": "classes/Src-Controller-PersonController.html#method___construct"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AprocessRequest\u0028\u0029",
            "name": "processRequest",
            "summary": "Funcionalidad\u0020que\u0020se\u0020encarga\u0020de\u0020procesar\u0020las\u0020peticiones\u0020de\u0020los\u0020usuarios.",
            "url": "classes/Src-Controller-PersonController.html#method_processRequest"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AgetAllUsers\u0028\u0029",
            "name": "getAllUsers",
            "summary": "Funcionalidad\u0020que\u0020se\u0020encarga\u0020de\u0020obtener\u0020todos\u0020los\u0020usuarios\u0020del\u0020sistema.",
            "url": "classes/Src-Controller-PersonController.html#method_getAllUsers"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "Funcionalidad\u0020que\u0020se\u0020encarga\u0020de\u0020obtener\u0020un\u0020usuario\u0020en\u0020base\u0020a\u0020una\u0020id\u0020proporcionada.",
            "url": "classes/Src-Controller-PersonController.html#method_getUser"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AcreateUserFromRequest\u0028\u0029",
            "name": "createUserFromRequest",
            "summary": "Funcionalidad\u0020que\u0020se\u0020encarga\u0020de\u0020crear\u0020un\u0020usuario\u0020de\u0020una\u0020petici\u00F3n\u0020http.",
            "url": "classes/Src-Controller-PersonController.html#method_createUserFromRequest"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AupdateUserFromRequest\u0028\u0029",
            "name": "updateUserFromRequest",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#method_updateUserFromRequest"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AdeleteUser\u0028\u0029",
            "name": "deleteUser",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#method_deleteUser"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AvalidatePerson\u0028\u0029",
            "name": "validatePerson",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#method_validatePerson"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AunprocessableEntityResponse\u0028\u0029",
            "name": "unprocessableEntityResponse",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#method_unprocessableEntityResponse"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003AnotFoundResponse\u0028\u0029",
            "name": "notFoundResponse",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#method_notFoundResponse"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#property_db"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003A\u0024requestMethod",
            "name": "requestMethod",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#property_requestMethod"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003A\u0024userId",
            "name": "userId",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#property_userId"
        },                {
            "fqsen": "\\Src\\Controller\\PersonController\u003A\u003A\u0024personGateway",
            "name": "personGateway",
            "summary": "",
            "url": "classes/Src-Controller-PersonController.html#property_personGateway"
        },                {
            "fqsen": "\\Src\\System\\DatabaseConnector",
            "name": "DatabaseConnector",
            "summary": "",
            "url": "classes/Src-System-DatabaseConnector.html"
        },                {
            "fqsen": "\\Src\\System\\DatabaseConnector\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Src-System-DatabaseConnector.html#method___construct"
        },                {
            "fqsen": "\\Src\\System\\DatabaseConnector\u003A\u003AgetConnection\u0028\u0029",
            "name": "getConnection",
            "summary": "",
            "url": "classes/Src-System-DatabaseConnector.html#method_getConnection"
        },                {
            "fqsen": "\\Src\\System\\DatabaseConnector\u003A\u003A\u0024dbConnection",
            "name": "dbConnection",
            "summary": "",
            "url": "classes/Src-System-DatabaseConnector.html#property_dbConnection"
        },                {
            "fqsen": "\\Src\\TableGateways\\PersonGateway",
            "name": "PersonGateway",
            "summary": "",
            "url": "classes/Src-TableGateways-PersonGateway.html"
        },                {
            "fqsen": "\\Src\\TableGateways\\PersonGateway\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Src-TableGateways-PersonGateway.html#method___construct"
        },                {
            "fqsen": "\\Src\\TableGateways\\PersonGateway\u003A\u003AfindAll\u0028\u0029",
            "name": "findAll",
            "summary": "",
            "url": "classes/Src-TableGateways-PersonGateway.html#method_findAll"
        },                {
            "fqsen": "\\Src\\TableGateways\\PersonGateway\u003A\u003Afind\u0028\u0029",
            "name": "find",
            "summary": "",
            "url": "classes/Src-TableGateways-PersonGateway.html#method_find"
        },                {
            "fqsen": "\\Src\\TableGateways\\PersonGateway\u003A\u003Ainsert\u0028\u0029",
            "name": "insert",
            "summary": "",
            "url": "classes/Src-TableGateways-PersonGateway.html#method_insert"
        },                {
            "fqsen": "\\Src\\TableGateways\\PersonGateway\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/Src-TableGateways-PersonGateway.html#method_update"
        },                {
            "fqsen": "\\Src\\TableGateways\\PersonGateway\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Src-TableGateways-PersonGateway.html#method_delete"
        },                {
            "fqsen": "\\Src\\TableGateways\\PersonGateway\u003A\u003A\u0024db",
            "name": "db",
            "summary": "",
            "url": "classes/Src-TableGateways-PersonGateway.html#property_db"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Src\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "namespaces/src-controller.html"
        },                {
            "fqsen": "\\Src",
            "name": "Src",
            "summary": "",
            "url": "namespaces/src.html"
        },                {
            "fqsen": "\\Src\\System",
            "name": "System",
            "summary": "",
            "url": "namespaces/src-system.html"
        },                {
            "fqsen": "\\Src\\TableGateways",
            "name": "TableGateways",
            "summary": "",
            "url": "namespaces/src-tablegateways.html"
        }            ]
);
